### Get all Users Data

GET http://localhost:3000/admin/users

### Get specific user data by name

GET http://localhost:3000/admin/users/ravi

### Update user data by specific name

POST http://localhost:3000/admin/user/ravi
content-type: application/json

{
"age": "700"
}

### Add new user
POST http://localhost:3000/admin/users/
content-type: application/json

{
    "name":"ravi",
    "age": "69"
}






