### Get all Users Data
GET http://localhost:3000/admin/users

###


GET http://localhost:3000/api/mohith




###


POST http://localhost:3000/api
content-type: application/json

{
"name": "rgk"
}




